[package]
name = "jimina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.5"

[profile.release]
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
